# NUM1=   int(input("enter num1:"))  #question 1
# NUM2=   int(input("enter num2:"))
# if NUM1>NUM2:
#     print(f"{NUM1} is great")
# elif NUM1<NUM2:
#     print(f"{NUM2} is great") 
# else:
#     print("both are equal")       

# gen = input("enter gender(m or f):-- ")       #question 2
# if gen == "m" or gen == "M":
#     print("male")
# elif gen == "f" or gen == "F":
#     print("female")
# else:
#     print(" hello mam(❁´◡`❁)😊")  


# num = int(input("enter the numbet"))   #question 3
# if num%2 == 0:
#     print(f"num: {num}, is even no,.")
# elif num%2!=0 and num<2:
#     print(f"num: {num}, is not  even no,.") 
# else:
#     print(f"num: {num}, is ODD no,.")       


# name = input("enter your name:")   ) #question 4
# age =  int(input("enter your age:")) 
# if age>=18:
#     print(f"hello {name} ,you can vote")
# else:
#     print(f"hello {name},sorry ,you can vote after {18-age} years")   
 

# yaer =  int(input("enter year :"))               #question 5
# if yaer%400==0 or yaer%4==0 and yaer%100!=0:
#     print(f"{yaer} is a leap year")
# else:
#  print("not-LEAP")


# temp =int(input("enter your vqalue:"))  #question 6
# if temp>=-5 and temp<=5:
#     print("very cold")
# elif temp>5 and temp <=18:
#     print("cold")  
# elif  temp>18 and temp<=30:
#     print("hot")    
# else:
#     print("very hot")    